# Publish all joint states -----------------------------------
joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

l_shoulder_pitch_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: l_shoulder_pitch_joint

l_shoulder_roll_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: l_shoulder_roll_joint
    
l_shoulder_yaw_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: l_shoulder_yaw_joint

l_elbow_pitch_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: l_elbow_pitch_joint

l_wrist_yaw_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: l_wrist_yaw_joint

l_wrist_roll_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: l_wrist_roll_joint

l_wrist_pitch_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: l_wrist_pitch_joint
