sophia:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    l_shoulder_pitch_joint_controller:
      type: effort_controllers/JointPositionController
      joint: l_shoulder_pitch_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    r_shoulder_pitch_joint_controller:
      type: effort_controllers/JointPositionController
      joint: r_shoulder_pitch_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    l_shoulder_roll_joint_controller:
      type: effort_controllers/JointPositionController
      joint: l_shoulder_roll_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    r_shoulder_roll_joint_controller:
      type: effort_controllers/JointPositionController
      joint: r_shoulder_roll_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    l_shoulder_yaw_joint_controller:
      type: effort_controllers/JointPositionController
      joint: l_shoulder_yaw_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    r_shoulder_yaw_joint_controller:
      type: effort_controllers/JointPositionController
      joint: r_shoulder_yaw_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    l_elbow_pitch_joint_controller:
      type: effort_controllers/JointPositionController
      joint: l_elbow_pitch_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    r_elbow_pitch_joint_controller:
      type: effort_controllers/JointPositionController
      joint: r_elbow_pitch_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    l_wrist_yaw_joint_controller:
      type: effort_controllers/JointPositionController
      joint: l_wrist_yaw_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    r_wrist_yaw_joint_controller:
      type: effort_controllers/JointPositionController
      joint: r_wrist_yaw_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    l_wrist_roll_joint_controller:
      type: effort_controllers/JointPositionController
      joint: l_wrist_roll_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    r_wrist_roll_joint_controller:
      type: effort_controllers/JointPositionController
      joint: r_wrist_roll_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    l_wrist_pitch_joint_controller:
      type: effort_controllers/JointPositionController
      joint: l_wrist_pitch_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    r_wrist_pitch_joint_controller:
      type: effort_controllers/JointPositionController
      joint: r_wrist_pitch_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
